### ISSUE TITLE
Feature request: JUnit XML outout

### ISSUE THREAD

**Issue by tobiasgies** [mafflerbach/testonaut#2]
It would be great to be able to have a test run's result returned as JUnit XML. That would allow me to embed testonaut tests in my Jenkins builds. Jenkins can natively read and interpret this quasi-standardized format.

**Comment by mafflerbach** [comment]
closed cuase: I've implemented a jenkins friendly output: https://github.com/mafflerbach/testonaut#jenkins-setup
